name: 'setup-signore'
description: 'setup-signore downloads, installs, and configures the signore signing service client'
inputs:
  github-token:
    description: 'The Github token to use to access the private signore repository.'
    required: false
    default: ''
  signer:
    description: 'The signer to add to the signore config (optional)'
    required: false
    default: ''
  version:
    description: 'The version of the signore CLI to install. Defaults to the most recent version.'
    required: false
    default: 'latest'
  archive-checksum:
    description: 'The expected SHA256 checksum to verify the signore CLI archive against.'
    required: false
    default: ''
outputs:
  version:
    description: 'The version of the signore CLI that was installed.'
runs:
  using: 'node12'
  main: 'dist/index.js'
