name: "Testing"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 20
    - run: npm ci
    - run: npm test
